services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6380:6379"
    networks:
      - transcendence

  db:
    image: postgres:16
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - ${DB_PORT}:5432
    env_file:
      - .env
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - DB_HOST=${DB_HOST}
    networks:
      - transcendence
    restart: always

  pgadmin:
    image: dpage/pgadmin4:latest
    restart: unless-stopped
    depends_on:
      - db
    ports:
      - 8081:80
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: password
    volumes:
      - pgadmin:/var/lib/pgadmin
    networks:
      - transcendence

  django:
    build:
      context: .
      dockerfile: requirements/django/Dockerfile
    command: /entrypoint.sh
    volumes:
      - ./mysite/:/var/www/django/
      - static_volume:/var/www/django/static/
      - media_volume:/var/www/django/media/
    container_name: django
    depends_on:
      - db
      - redis
    env_file:
      - .env
    networks:
      - transcendence
    restart: always

  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - django
    ports:
      - "8443:443"
    volumes:
      - static_volume:/var/www/django/static/
      - media_volume:/var/www/django/media/
      - ./requirements/nginx/:/etc/nginx/sites-enabled/
    networks:
      - transcendence
    restart: always

networks:
    transcendence:
        driver: bridge
volumes:
  postgres_data:
    driver: local
  static_volume:
  media_volume:
  pgadmin:
    driver: local
