services:
  redis:
    image: redis:7
    container_name: redis
    ports:
      - "6379:6379"
    networks:
      - transcendence
  db:
    image: postgres
    container_name: postgres
    volumes:
      - ./data/db:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    env_file:
      - .env
    networks:
      - transcendence
    restart: always
  django:
    build:
      context: .
      dockerfile: requirements/django/Dockerfile
    container_name: django
    depends_on:
      - db
      - redis
    ports:
      - "8001:8001"
    networks:
      - transcendence
    restart: always
  nginx:
    build:
      context: .
      dockerfile: requirements/nginx/Dockerfile
    container_name: nginx
    depends_on:
      - django
    ports:
      - "443:443"
    volumes:
      - ./main/mysite/main/static/:/var/www/django/static/
      - ./main/mysite/main/media/:/var/www/django/media/
      - ./requirements/nginx/conf/:/etc/nginx/sites-enabled/
    networks:
      - transcendence
    restart: always

networks:
    transcendence:
        driver: bridge
