# Generated by Django 5.1.1 on 2025-01-11 20:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpong',
            name='auth_method',
            field=models.CharField(choices=[('site', 'Site Registration'), ('oauth', '42 API')], default='site', max_length=10),
        ),
        migrations.AddField(
            model_name='userpong',
            name='oauth_id',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='userpong',
            name='password',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
