# Generated by Django 5.1.1 on 2025-01-21 18:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('game_id', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('is_active', models.BooleanField(default=True)),
                ('game_type', models.CharField(default='local', max_length=50)),
                ('p1_score', models.IntegerField(default=0)),
                ('p2_score', models.IntegerField(default=0)),
            ],
        ),
    ]
