# Generated by Django 5.1.1 on 2024-11-28 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_match_user1_remove_match_user1_score_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='game_type',
            field=models.CharField(default='localgame', max_length=50),
        ),
    ]
