# Generated by Django 5.1.1 on 2024-12-04 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_match_game_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='match',
            name='p1_score',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='match',
            name='p2_score',
            field=models.IntegerField(default=0),
        ),
    ]
